SYNCQT.HEADER_FILES = ../../include/QtDAI/qtdai.h ../../include/QtDAI/dai
SYNCQT.HEADER_CLASSES = ../../include/QtDAI/QtDAI
SYNCQT.PRIVATE_HEADER_FILES =
SYNCQT.QPA_HEADER_FILES = 
SYNCQT.INJECTIONS = 
